//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryFunctionality
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string StateProvinceName { get; set; }
        public string CountryRegionName { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> HomeOwnerflag { get; set; }
        public Nullable<int> NumberCarsOwned { get; set; }
        public Nullable<int> NumberChildrenAtHome { get; set; }
        public Nullable<int> TotalChildren { get; set; }
        public Nullable<int> YearlyIncome { get; set; }
    }
}
